---
# This playbook deploys a kubernetes cluster with the default addons.

# Install yum-repo
- hosts: all
  roles:
    - role: yum-repo
      when: ansible_os_family == "RedHat"
  tags:
    - yum-repo

# Install sslcert
- hosts: sslhost
  become: true
  roles:
    - role: sslcert 
  tags:
    - sslcert

# Install etcd
- hosts: etcd
  become: true
  roles:
    - role: etcd
  tags:
    - etcd

# Install container runtime
- hosts: all
  become: true
  roles:
    - { role: runtime-env }
    - { role: docker, when: not containerd.enabled }
    - { role: containerd, when: containerd.enabled }
  tags:
    - runtime

# install haproxy
- hosts: masters
  become: true
  roles:
    - { role: haproxy, when: haproxy.enabled }
  tags:
    - haproxy

# install keepalived
- hosts: masters
  become: true
  roles:
    - { role: keepalived, when: keepalived.enabled }
  tags:
    - keepalived

# install kubernetes master services
- hosts: masters
  become: true
  roles:
    - role: master
  tags:
    - master

# install kubernetes on the nodes
- hosts: node
  become: true
  roles:
    - role: node
  tags:
    - node
